version: '3.9'
services:
  db:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb
  apache:
    image: httpd
  linux:
    image: ubuntu
  busybox:
    image: busybox